#!/usr/bin/perl
#
# mtrr : MTRR register setting script for PROGRAPE-4
#
# Copyright (C) 2006-2007 Tsuyoshi Hamada. All rights reserved.
# 
# No warranty is attached; 
#
#

my $devid   = 0;
my $bar;
my $cmd;
my $exe;

if(@ARGV){
    sprintf($devid, "%d", $ARGV[0]);
}

$bar = 1;

my $adr=0, $size;

$cmd = "ifpga_get_barinfo $devid $bar";
$exe = `$cmd`;
chomp($exe);
$adr = $exe;

$cmd = "ifpga_get_barinfo $devid $bar 1";
$exe = `$cmd`;
chomp($exe);
$size = $exe;

print "BAR1 start at $adr, size $size bytes\n";

if( ($adr eq '') || ($adr eq '0x0') || ($adr eq "0xffffffff")){
    print "discontinued\n";
    exit(-1);
}


$cmd = "echo \"base=$adr size=$size type=write-combining\" >| /proc/mtrr";
print  $cmd. "\n\n";
print `$cmd`;

$cmd = "cat /proc/mtrr";
print `$cmd`;

1;
